services:
  cors:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    entrypoint: ["node", "server.js", "argumento1", "argumento2"]
